_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 12
                - 41
                - 53
                - 55
            "2":
                - 1
                - 2
                - 3
                - 5
                - 12
                - 41
                - 53
                - 55
            "3":
                - 17
                - 23
                - 55
            "4": 3.10.12
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
